CREATE TABLE IF NOT EXISTS `avored_pisss`  (
  `id` INT(10)  auth_increment PRIMARY KEY NOT NULL ,
  `user_id` INT (10),
  `COL` CHAR (50),
  `LEU` FLOAT(7,3),
  `PRO` VARCHAR (50),
  `BLD` VARCHAR (50),
  `KET` VARCHAR (50),
  `SG`  FLOAT (7,3),
  `NIT` VARCHAR (50),
  `GLU-` VARCHAR (50),
  `PH`  FLOAT (7,3),
  `URO` VARCHAR (50),
  `BIL` VARCHAR (50),
  `RBC` FLOAT (7,3),
  `check_time` TIMESTAMP ,
  `created_at` TIMESTAMP ,
  `updated_at` TIMESTAMP
)

create table if not EXISTS  `avored_liver_kidneys`(
  `id` INT (10) auto_increment primary key not null,
  `user_id` INT (10),
  `TP` FLOAT (7,3),
  `G` FLOAT (7,3),
  `ALB` FLOAT (7,3),
  `AST` FLOAT (7,3),
  `ALT` FLOAT (7,3),
  `STB` FLOAT (7,3),
  `BDIL` FLOAT (7,3),
  `CHE` FLOAT (7,3),
  `Scr` FLOAT (7,3),
  `Urea` FLOAT (7,3),
  `SUA`  FLOAT (7,3),
  `CysC` FLOAT (7,3),
  `CHOL`  FLOAT (7,3),
  `eGFR` FLOAT (7,3),
  `check_time` timestamp,
  `created_at` timestamp,
  `updated_at` TIMESTAMP
)

create table if not EXISTS  `avored_bloods`(
  `id` INT (10) auto_increment primary key not null,
  `user_id` INT (10),
  `RBC` FLOAT (7,3),
  `HCT` FLOAT (7,3),
  `MCV` FLOAT (7,3),
  `RDW-CV` FLOAT (7,3),
  `HGB` FLOAT (7,3),
  `MCH` FLOAT (7,3),
  `MCHC` FLOAT (7,3),
  `WBC` FLOAT (7,3),
  `MO` FLOAT (7,3),
  `MO#` FLOAT (7,3),
  `MONO`  FLOAT (7,3),
  `NEUT` FLOAT (7,3),
  `NE`  FLOAT (7,3),
  `LY` FLOAT (7,3),
  `LY%` FLOAT (7,3),
  `LY#` FLOAT (7,3),
  `PLT` FLOAT (7,3),
  `MPV` FLOAT (7,3),
  `PDW` FLOAT (7,3),
  `PCT` FLOAT (7,3),
  `P-LCR` FLOAT (7,3),
  `EO` FLOAT (7,3),
  `BA#` FLOAT (7,3),
  `BA` FLOAT (7,3),
  `NE#` FLOAT (7,3),
  `NRBC` FLOAT (7,3),
  `NRBC#` FLOAT (7,3),
  `check_time` timestamp,
  `created_at` timestamp,
  `updated_at` TIMESTAMP
)


create table if not EXISTS  `avored_biochemistrys`(
  `id` INT (10) auto_increment primary key not null,
  `user_id` INT (10),
  `LDH` FLOAT (7,3),
  `AST` FLOAT (7,3),
  `ALT` FLOAT (7,3),
  `GGT` FLOAT (7,3),
  `CK` FLOAT (7,3),
  `CK-MB` FLOAT (7,3),
  `HBDH` FLOAT (7,3),
  `AMY` FLOAT (7,3),
  `ALP` FLOAT (7,3),
  `TBIL` FLOAT (7,3),
  `IBIL`  FLOAT (7,3),
  `TBA` FLOAT (7,3),
  `TP`  FLOAT (7,3),
  `ALB` FLOAT (7,3),
  `GLB` FLOAT (7,3),
  `A/G` FLOAT (7,3),
  `BUN` FLOAT (7,3),
  `CREA` FLOAT (7,3),
  `B/C` FLOAT (7,3),
  `URIC` FLOAT (7,3),
  `TG` FLOAT (7,3),
  `HDL-C` FLOAT (7,3),
  `LDL-C` FLOAT (7,3),
  `Na` FLOAT (7,3),
  `K` FLOAT (7,3),
  `CL` FLOAT (7,3),
  `CO2` FLOAT (7,3),
  `Ca` FLOAT (7,3),
  `Mg` FLOAT (7,3),
  `PO4` FLOAT (7,3),
  `AG` FLOAT (7,3),
  `OSM` FLOAT (7,3),
  `GLU` FLOAT (7,3),
  `check_time` timestamp,
  `created_at` timestamp,
  `updated_at` TIMESTAMP
)
CREATE TABLE if EXISTS `avored_check_explain`(
  `id` INT (10) auto_increment PRIMARY KEY NOT NULL ,
  `name` VARCHAR (50) not null,
  `refer_min` VARCHAR (20),
  `refer_max` VARCHAR (20),
  `unit` VARCHAR (20),
  `check_time` timestamp,
  `created_at` TIMESTAMP ,
  `updated_at` TIMESTAMP
)

